In [4]:
# Modules to scrape the URL
from urllib.request import urlopen
from bs4 import BeautifulSoup as bs

In [18]:
import pandas as pd
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt

In [53]:
# 2019 Data

url2019 = 'https://www.pro-football-reference.com/awards/2019-nfl-top-100.htm'
html2019 = urlopen(url2019)
stats_page_2019 = bs(html2019)

column_headers_2019 = stats_page_2019.findAll('tr')[1]
column_headers_2019 = [i.getText() for i in column_headers_2019.findAll('th')]
print(column_headers_2019)

['Rank', 'Pos', 'Player', 'Tm', 'G', 'GS', 'Cmp', 'Att', 'Yds', 'TD', 'Int', 'Att', 'Yds', 'TD', 'Rec', 'Yds', 'TD', 'Solo', 'Sk', 'Int']

In [30]:
rows_2019 = stats_page_2019.findAll('tr')[2:]

In [49]:
stats_2019 = []
for i in range(len(rows_2019)):
    stats_2019.append([col.getText() for col in rows_2019[i].findAll('td')])

In [152]:
df_2019 = pd.DataFrame(stats_2019, columns=column_headers_2019[1:])

# Add what year it is for when we combine the data frames
df_2019.insert(0, column="Year", value="2019")

# Add the player's rank to the data frame
df_2019.insert(1, column="Rank", value = df_2019.index +1)

In [153]:
df_2019.head()

,Year,Rank,Pos,Player,Tm,G,GS,Cmp,Att,Yds,...,Int,Att,Yds,TD,Rec,Yds,TD,Solo,Sk,Int
0,2019,1,DT,Aaron Donald,LAR,16,16,0,0,0,...,0,0,0,0,0,0,0,29,12.5,0
1,2019,2,QB,Drew Brees,NOR,11,11,281,378,2979,...,4,9,-4,1,0,0,0,0,0.0,0
2,2019,3,DE,Khalil Mack,CHI,16,16,0,0,0,...,0,0,0,0,0,0,0,40,8.5,0
3,2019,4,QB,Patrick Mahomes,KAN,14,14,319,484,4031,...,5,43,218,2,0,0,0,0,0.0,0
4,2019,5,RB,Todd Gurley,LAR,15,15,0,0,0,...,0,223,857,12,31,207,2,0,0.0,0

In [154]:
df_2019.columns

Index(['Year', 'Rank', 'Pos', 'Player', 'Tm', 'G', 'GS', 'Cmp', 'Att', 'Yds',
       'TD', 'Int', 'Att', 'Yds', 'TD', 'Rec', 'Yds', 'TD', 'Solo', 'Sk',
       'Int'],
      dtype='object')

In [129]:
# 2018 Data

url2018 = 'https://www.pro-football-reference.com/awards/2018-nfl-top-100.htm'
html2018 = urlopen(url2018)
stats_page_2018 = bs(html2018)

column_headers_2018 = stats_page_2018.findAll('tr')[1]
column_headers_2018 = [i.getText() for i in column_headers_2018.findAll('th')]
print(column_headers_2018)

['Rank', 'Pos', 'Player', 'Tm', 'G', 'GS', 'Cmp', 'Att', 'Yds', 'TD', 'Int', 'Att', 'Yds', 'TD', 'Rec', 'Yds', 'TD', 'Solo', 'Sk', 'Int']

In [155]:
rows_2018 = stats_page_2018.findAll('tr')[2:]

stats_2018 = []
for i in range(len(rows_2018)):
    stats_2018.append([col.getText() for col in rows_2018[i].findAll('td')])
    
df_2018 = pd.DataFrame(stats_2018, columns=column_headers_2018[1:])

# Add what year it is for when we combine the data frames
df_2018.insert(0, column="Year", value="2018")

# Add the player's rank to the data frame
df_2018.insert(1, column="Rank", value = df_2018.index +1)

df_2018.head()

,Year,Rank,Pos,Player,Tm,G,GS,Cmp,Att,Yds,...,Int,Att,Yds,TD,Rec,Yds,TD,Solo,Sk,Int
0,2018,1,QB,Tom Brady,NWE,16,16,375,570,4355,...,11,23,35,2,1,6,0,0,0.0,0
1,2018,2,WR,Antonio Brown,PIT,15,15,0,1,0,...,0,0,0,0,104,1297,15,0,0.0,0
2,2018,3,QB,Carson Wentz,PHI,11,11,279,401,3074,...,7,34,93,0,1,4,0,0,0.0,0
3,2018,4,WR,Julio Jones,ATL,16,16,0,0,0,...,0,2,12,0,113,1677,8,0,0.0,0
4,2018,5,RB,Le'Veon Bell,,,,,,,...,,,,,,,,,,

In [156]:
# 2017 Data

url2017 = 'https://www.pro-football-reference.com/awards/2017-nfl-top-100.htm'
html2017 = urlopen(url2017)
stats_page_2017 = bs(html2017)

column_headers_2017 = stats_page_2017.findAll('tr')[1]
column_headers_2017 = [i.getText() for i in column_headers_2017.findAll('th')]

rows_2017 = stats_page_2017.findAll('tr')[2:]

stats_2017 = []
for i in range(len(rows_2017)):
    stats_2017.append([col.getText() for col in rows_2017[i].findAll('td')])
    
df_2017 = pd.DataFrame(stats_2017, columns=column_headers_2017[1:])

# Add what year it is for when we combine the data frames
df_2017.insert(0, column="Year", value="2017")

# Add the player's rank to the data frame
df_2017.insert(1, column="Rank", value = df_2017.index +1)

df_2017.head()

,Year,Rank,Pos,Player,Tm,G,GS,Cmp,Att,Yds,...,Int,Att,Yds,TD,Rec,Yds,TD,Solo,Sk,Int
0,2017,1,QB,Tom Brady,NWE,16,16,385,581,4577,...,8,25,28,0,0,0,0,0,0.0,0
1,2017,2,LB,Von Miller,DEN,16,16,0,0,0,...,0,0,0,0,0,0,0,51,10.0,0
2,2017,3,WR,Julio Jones,ATL,16,16,0,0,0,...,0,1,15,0,88,1444,3,0,0.0,0
3,2017,4,WR,Antonio Brown,PIT,14,14,0,0,0,...,0,0,0,0,101,1533,9,0,0.0,0
4,2017,5,OLB,Khalil Mack,OAK,16,16,0,0,0,...,0,0,0,0,0,0,0,61,10.5,0

In [157]:
# 2016 Data

url2016 = 'https://www.pro-football-reference.com/awards/2016-nfl-top-100.htm'
html2016 = urlopen(url2016)
stats_page_2016 = bs(html2016)

column_headers_2016 = stats_page_2016.findAll('tr')[1]
column_headers_2016 = [i.getText() for i in column_headers_2016.findAll('th')]

rows_2016 = stats_page_2016.findAll('tr')[2:]

stats_2016 = []
for i in range(len(rows_2016)):
    stats_2016.append([col.getText() for col in rows_2016[i].findAll('td')])
    
df_2016 = pd.DataFrame(stats_2016, columns=column_headers_2016[1:])


# Add what year it is for when we combine the data frames
df_2016.insert(0, column="Year", value="2016")

# Add the player's rank to the data frame
df_2016.insert(1, column="Rank", value = df_2016.index +1)

df_2016.head()

,Year,Rank,Pos,Player,Tm,G,GS,Cmp,Att,Yds,...,Int,Att,Yds,TD,Rec,Yds,TD,Solo,Sk,Int
0,2016,1,QB,Cam Newton,CAR,15,14,270,510,3509,...,14,90,359,5,0,0,0,0,0.0,0
1,2016,2,QB,Tom Brady,NWE,12,12,291,432,3554,...,2,28,64,0,0,0,0,0,0.0,0
2,2016,3,DE,J.J. Watt,HOU,3,3,0,0,0,...,0,0,0,0,0,0,0,1,1.5,0
3,2016,4,WR,Antonio Brown,PIT,15,15,0,0,0,...,0,3,9,0,106,1284,12,0,0.0,0
4,2016,5,RB,Adrian Peterson,MIN,3,3,0,0,0,...,0,37,72,0,3,8,0,0,0.0,0

In [158]:
# 2015 Data


url2015 = 'https://www.pro-football-reference.com/awards/2015-nfl-top-100.htm'
html2015 = urlopen(url2015)
stats_page_2015 = bs(html2015)

column_headers_2015 = stats_page_2015.findAll('tr')[1]
column_headers_2015 = [i.getText() for i in column_headers_2015.findAll('th')]

rows_2015 = stats_page_2015.findAll('tr')[2:]

stats_2015 = []
for i in range(len(rows_2015)):
    stats_2015.append([col.getText() for col in rows_2015[i].findAll('td')])
    
df_2015 = pd.DataFrame(stats_2015, columns=column_headers_2015[1:])

# Add what year it is for when we combine the data frames
df_2015.insert(0, column="Year", value="2015")

# Add the player's rank to the data frame
df_2015.insert(1, column="Rank", value = df_2015.index +1)

df_2015.head()

,Year,Rank,Pos,Player,Tm,G,GS,Cmp,Att,Yds,...,Int,Att,Yds,TD,Rec,Yds,TD,Solo,Sk,Int
0,2015,1,DE,J.J. Watt,HOU,16,16,0,0,0,...,0,0,0,0,0,0,0,57,17.5,0
1,2015,2,QB,Aaron Rodgers,GNB,16,16,347,572,3821,...,8,58,344,1,0,0,0,0,0.0,0
2,2015,3,QB,Tom Brady,NWE,16,16,402,624,4770,...,7,34,53,3,1,36,0,0,0.0,0
3,2015,4,RB,DeMarco Murray,PHI,15,8,0,0,0,...,0,193,702,6,44,322,1,0,0.0,0
4,2015,5,QB,Peyton Manning,DEN,10,9,198,331,2249,...,17,6,-6,0,0,0,0,0,0.0,0

In [159]:
# 2014 Data


url2014 = 'https://www.pro-football-reference.com/awards/2014-nfl-top-100.htm'
html2014 = urlopen(url2014)
stats_page_2014 = bs(html2014)

column_headers_2014 = stats_page_2014.findAll('tr')[1]
column_headers_2014 = [i.getText() for i in column_headers_2014.findAll('th')]

rows_2014 = stats_page_2014.findAll('tr')[2:]

stats_2014 = []
for i in range(len(rows_2014)):
    stats_2014.append([col.getText() for col in rows_2014[i].findAll('td')])
    
df_2014 = pd.DataFrame(stats_2014, columns=column_headers_2014[1:])

# Add what year it is for when we combine the data frames
df_2014.insert(0, column="Year", value="2014")

# Add the player's rank to the data frame
df_2014.insert(1, column="Rank", value = df_2014.index +1)

df_2014.head()

,Year,Rank,Pos,Player,Tm,G,GS,Cmp,Att,Yds,...,Int,Att,Yds,TD,Rec,Yds,TD,Solo,Sk,Int
0,2014,1,QB,Peyton Manning,DEN,16,16,395,597,4727,...,15,24,-24,0,0,0,0,0,0.0,0
1,2014,2,WR,Calvin Johnson,DET,13,13,0,0,0,...,0,0,0,0,71,1077,8,0,0.0,0
2,2014,3,QB,Tom Brady,NWE,16,16,373,582,4109,...,9,36,57,0,0,0,0,0,0.0,0
3,2014,4,RB,Adrian Peterson,MIN,1,1,0,0,0,...,0,21,75,0,2,18,0,0,0.0,0
4,2014,5,RB,LeSean McCoy,PHI,16,16,0,0,0,...,0,312,1319,5,28,155,0,0,0.0,0

In [160]:
# 2013 Data


url2013 = 'https://www.pro-football-reference.com/awards/2013-nfl-top-100.htm'
html2013 = urlopen(url2013)
stats_page_2013 = bs(html2013)

column_headers_2013 = stats_page_2013.findAll('tr')[1]
column_headers_2013 = [i.getText() for i in column_headers_2013.findAll('th')]

rows_2013 = stats_page_2013.findAll('tr')[2:]

stats_2013 = []
for i in range(len(rows_2013)):
    stats_2013.append([col.getText() for col in rows_2013[i].findAll('td')])
    
df_2013 = pd.DataFrame(stats_2013, columns=column_headers_2013[1:])

# Add what year it is for when we combine the data frames
df_2013.insert(0, column="Year", value="2013")

# Add the player's rank to the data frame
df_2013.insert(1, column="Rank", value = df_2013.index +1)

df_2013.head()

,Year,Rank,Pos,Player,Tm,G,GS,Cmp,Att,Yds,...,Int,Att,Yds,TD,Rec,Yds,TD,Solo,Sk,Int
0,2013,1,RB,Adrian Peterson,MIN,14,14,0,0,0,...,0,279,1266,10,29,171,1,0,0.0,0
1,2013,2,QB,Peyton Manning,DEN,16,16,450,659,5477,...,10,32,-31,1,0,0,0,0,0.0,0
2,2013,3,WR,Calvin Johnson,DET,14,14,0,0,0,...,0,0,0,0,84,1492,12,0,0.0,0
3,2013,4,QB,Tom Brady,NWE,16,16,380,628,4343,...,11,32,18,0,0,0,0,0,0.0,0
4,2013,5,DE,J.J. Watt,HOU,16,16,0,0,0,...,0,0,0,0,0,0,0,65,10.5,0

In [161]:
# 2012 Data


url2012 = 'https://www.pro-football-reference.com/awards/2012-nfl-top-100.htm'
html2012 = urlopen(url2012)
stats_page_2012 = bs(html2012)

column_headers_2012 = stats_page_2012.findAll('tr')[1]
column_headers_2012 = [i.getText() for i in column_headers_2012.findAll('th')]

rows_2012 = stats_page_2012.findAll('tr')[2:]

stats_2012 = []
for i in range(len(rows_2012)):
    stats_2012.append([col.getText() for col in rows_2012[i].findAll('td')])
    
df_2012 = pd.DataFrame(stats_2012, columns=column_headers_2012[1:])

# Add what year it is for when we combine the data frames
df_2012.insert(0, column="Year", value="2012")

# Add the player's rank to the data frame
df_2012.insert(1, column="Rank", value = df_2012.index +1)

df_2012.head()

,Year,Rank,Pos,Player,Tm,G,GS,Cmp,Att,Yds,...,Int,Att,Yds,TD,Rec,Yds,TD,Solo,Sk,Int
0,2012,1,QB,Aaron Rodgers,GNB,16,16,371,552,4295,...,8,54,259,2,1,-1,0,0,0.0,0
1,2012,2,QB,Drew Brees,NOR,16,16,422,670,5177,...,19,15,5,1,0,0,0,0,0.0,0
2,2012,3,WR,Calvin Johnson,DET,16,16,0,0,0,...,0,0,0,0,122,1964,5,0,0.0,0
3,2012,4,QB,Tom Brady,NWE,16,16,401,637,4827,...,8,23,32,4,0,0,0,0,0.0,0
4,2012,5,CB,Darrelle Revis,NYJ,2,2,0,0,0,...,0,0,0,0,0,0,0,9,0.0,1

In [162]:
# 2011 Data


url2011 = 'https://www.pro-football-reference.com/awards/2011-nfl-top-100.htm'
html2011 = urlopen(url2011)
stats_page_2011 = bs(html2011)

column_headers_2011 = stats_page_2011.findAll('tr')[1]
column_headers_2011 = [i.getText() for i in column_headers_2011.findAll('th')]

rows_2011 = stats_page_2011.findAll('tr')[2:]

stats_2011 = []
for i in range(len(rows_2011)):
    stats_2011.append([col.getText() for col in rows_2011[i].findAll('td')])
    
df_2011 = pd.DataFrame(stats_2011, columns=column_headers_2011[1:])

# Add what year it is for when we combine the data frames
df_2011.insert(0, column="Year", value="2011")

# Add the player's rank to the data frame
df_2011.insert(1, column="Rank", value = df_2011.index +1)

df_2011.head()

,Year,Rank,Pos,Player,Tm,G,GS,Cmp,Att,Yds,...,Int,Att,Yds,TD,Rec,Yds,TD,Solo,Sk,Int
0,2011,1,QB,Tom Brady,NWE,16,16,401,611,5235,...,12,43,109,3,0,0,0,0,0.0,0
1,2011,2,QB,Peyton Manning,,,,,,,...,,,,,,,,,,
2,2011,3,RB,Adrian Peterson,MIN,12,12,0,0,0,...,0,208,970,12,18,139,1,0,0.0,0
3,2011,4,LB,Ray Lewis,BAL,12,12,0,0,0,...,0,0,0,0,0,0,0,72,2.0,1
4,2011,5,S,Ed Reed,BAL,16,16,0,0,0,...,0,0,0,0,0,0,0,44,1.0,3

In [163]:
# Combine all of the year data frames into one big main_df to start with visualizations

main_df = pd.concat([df_2019, df_2018, df_2017, df_2016, df_2015, df_2014, df_2013, df_2012, df_2011], axis=0)
main_df

,Year,Rank,Pos,Player,Tm,G,GS,Cmp,Att,Yds,...,Int,Att,Yds,TD,Rec,Yds,TD,Solo,Sk,Int
0,2019,1,DT,Aaron Donald,LAR,16,16,0,0,0,...,0,0,0,0,0,0,0,29,12.5,0
1,2019,2,QB,Drew Brees,NOR,11,11,281,378,2979,...,4,9,-4,1,0,0,0,0,0.0,0
2,2019,3,DE,Khalil Mack,CHI,16,16,0,0,0,...,0,0,0,0,0,0,0,40,8.5,0
3,2019,4,QB,Patrick Mahomes,KAN,14,14,319,484,4031,...,5,43,218,2,0,0,0,0,0.0,0
4,2019,5,RB,Todd Gurley,LAR,15,15,0,0,0,...,0,223,857,12,31,207,2,0,0.0,0
5,2019,6,QB,Tom Brady,NWE,16,16,373,613,4057,...,8,26,34,3,0,0,0,0,0.0,0
6,2019,7,WR,Antonio Brown,NWE,1,0,0,0,0,...,0,1,5,0,4,56,1,0,0.0,0
7,2019,8,QB,Aaron Rodgers,GNB,16,16,353,569,4002,...,4,46,183,1,0,0,0,0,0.0,0
8,2019,9,WR,Julio Jones,ATL,15,15,0,0,0,...,0,2,-3,0,99,1394,6,0,0.0,0
9,2019,10,LB,Von Miller,DEN,15,15,0,0,0,...,0,0,0,0,0,0,0,33,8.0,0
10,2019,11,WR,DeAndre Hopkins,HOU,15,15,1,2,6,...,1,2,18,0,104,1165,7,0,0.0,0
11,2019,12,DE,J.J. Watt,HOU,8,8,0,0,0,...,0,0,0,0,0,0,0,15,4.0,0
12,2019,13,WR,Michael Thomas,NOR,16,15,0,0,0,...,0,1,-9,0,149,1725,9,0,0.0,0
13,2019,14,RB,Alvin Kamara,NOR,14,9,1,1,13,...,0,171,797,5,81,533,1,0,0.0,0
14,2019,15,LB,Bobby Wagner,SEA,16,16,0,0,0,...,0,0,0,0,0,0,0,86,3.0,1
15,2019,16,RB,Saquon Barkley,NYG,13,13,0,0,0,...,0,217,1003,6,52,438,2,0,0.0,0
16,2019,17,QB,Philip Rivers,LAC,16,16,390,591,4615,...,20,12,29,0,0,0,0,0,0.0,0
17,2019,18,RB,Ezekiel Elliott,DAL,16,16,0,0,0,...,0,301,1357,12,54,420,2,0,0.0,0
18,2019,19,WR,Tyreek Hill,KAN,12,12,0,0,0,...,0,8,23,0,58,860,7,0,0.0,0
19,2019,20,QB,Andrew Luck,,,,,,,...,,,,,,,,,,
20,2019,21,TE,Travis Kelce,KAN,16,16,0,0,0,...,0,1,4,1,97,1229,5,0,0.0,0
21,2019,22,CB,Stephon Gilmore,NWE,16,16,0,0,0,...,0,0,0,0,0,0,0,44,0.0,6
22,2019,23,WR,Odell Beckham Jr.,CLE,16,15,1,2,20,...,0,3,10,0,74,1035,4,0,0.0,0
23,2019,24,LB,Luke Kuechly,CAR,16,16,0,0,0,...,0,0,0,0,0,0,0,81,0.0,2
24,2019,25,QB,Russell Wilson,SEA,16,16,341,516,4110,...,5,75,342,3,0,0,0,0,0.0,0
25,2019,26,LB,Darius Leonard,IND,13,13,0,0,0,...,0,0,0,0,0,0,0,71,5.0,5
26,2019,27,CB,Jalen Ramsey,,12,11,0,0,0,...,0,0,0,0,0,0,0,44,0.0,1
27,2019,28,DT,Fletcher Cox,PHI,16,16,0,0,0,...,0,0,0,0,0,0,0,26,3.5,0
28,2019,29,TE,George Kittle,SFO,14,14,0,0,0,...,0,5,22,0,85,1053,5,0,0.0,0
29,2019,30,SS,Eddie Jackson,CHI,16,16,0,0,0,...,0,0,0,0,0,0,0,51,1.0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,2011,71,DE,Mario Williams,HOU,5,5,0,0,0,...,0,0,0,0,0,0,0,10,5.0,0
71,2011,72,QB,Tony Romo,DAL,16,16,346,522,4184,...,10,22,46,1,0,0,0,0,0.0,0
72,2011,73,DE,Trent Cole,PHI,14,14,0,0,0,...,0,0,0,0,0,0,0,41,11.0,0
73,2011,74,WR,Greg Jennings,GNB,13,13,0,0,0,...,0,0,0,0,67,949,9,0,0.0,0
74,2011,75,DT,Jay Ratliff,DAL,16,16,0,0,0,...,0,0,0,0,0,0,0,29,2.0,0
75,2011,76,WR,Santonio Holmes,NYJ,16,16,0,0,0,...,0,3,27,0,51,654,8,0,0.0,0
76,2011,77,G,Chris Snee,NYG,15,15,0,0,0,...,0,0,0,0,0,0,0,0,0.0,0
77,2011,78,TE,Dallas Clark,IND,11,10,0,0,0,...,0,0,0,0,34,352,2,0,0.0,0
78,2011,79,T,D'Brickashaw Ferguson,NYJ,16,16,0,0,0,...,0,0,0,0,0,0,0,0,0.0,0
79,2011,80,DE,Jared Allen,MIN,16,16,0,0,0,...,0,0,0,0,0,0,0,48,22.0,1
80,2011,81,DT,B.J. Raji,GNB,16,16,0,0,0,...,0,1,1,1,0,0,0,14,3.0,0
81,2011,82,LB,LaMarr Woodley,PIT,10,10,0,0,0,...,0,0,0,0,0,0,0,26,9.0,1
82,2011,83,WR,Mike Williams,TAM,16,15,0,0,0,...,0,1,3,0,65,771,3,0,0.0,0
83,2011,84,WR,Josh Cribbs,CLE,16,7,0,0,0,...,0,7,25,0,41,518,4,10,0.0,0
84,2011,85,DE,Jason Babin,PHI,16,16,0,0,0,...,0,0,0,0,0,0,0,35,18.0,0
85,2011,86,QB,Josh Freeman,TAM,15,15,346,551,3592,...,22,55,238,4,0,-4,0,0,0.0,0
86,2011,87,T,Jordan Gross,CAR,15,15,0,0,0,...,0,0,0,0,0,0,0,0,0.0,0
87,2011,88,TE,Vernon Davis,SFO,16,16,0,0,0,...,0,2,-5,0,67,792,6,0,0.0,0
88,2011,89,S,Adrian Wilson,ARI,16,16,0,0,0,...,0,0,0,0,0,0,0,48,0.0,1
89,2011,90,QB,Joe Flacco,BAL,16,16,312,542,3610,...,12,39,88,1,1,-8,0,0,0.0,0
90,2011,91,WR,Terrell Owens,,,,,,,...,,,,,,,,,,
91,2011,92,LB,Lance Briggs,CHI,16,16,0,0,0,...,0,0,0,0,0,0,0,86,0.0,1
92,2011,93,S,Eric Berry,KAN,1,1,0,0,0,...,0,0,0,0,0,0,0,,0.0,0
93,2011,94,RB,Frank Gore,SFO,16,15,0,0,0,...,0,282,1211,8,17,114,0,0,0.0,0
94,2011,95,LB,Jon Beason,CAR,1,1,0,0,0,...,0,0,0,0,0,0,0,4,0.0,0
95,2011,96,S,Nick Collins,GNB,2,2,0,0,0,...,0,0,0,0,0,0,0,9,0.0,0
96,2011,97,LB,Shaun Phillips,SDG,12,12,0,0,0,...,0,0,0,0,0,0,0,30,3.5,2
97,2011,98,RB,Darren McFadden,OAK,7,7,0,0,0,...,0,113,614,4,19,154,1,0,0.0,0
98,2011,99,T,Chad Clifton,GNB,6,6,0,0,0,...,0,0,0,0,0,0,0,,0.0,0
99,2011,100,QB,Donovan McNabb,MIN,6,6,94,156,1026,...,2,14,59,1,0,0,0,0,0.0,0

In [164]:
main_df.shape

(899, 21)

In [165]:
main_df.columns

Index(['Year', 'Rank', 'Pos', 'Player', 'Tm', 'G', 'GS', 'Cmp', 'Att', 'Yds',
       'TD', 'Int', 'Att', 'Yds', 'TD', 'Rec', 'Yds', 'TD', 'Solo', 'Sk',
       'Int'],
      dtype='object')

In [166]:
# make sure no additional columns were created
df_2011.shape

(100, 21)

In [167]:
df_2011.columns

Index(['Year', 'Rank', 'Pos', 'Player', 'Tm', 'G', 'GS', 'Cmp', 'Att', 'Yds',
       'TD', 'Int', 'Att', 'Yds', 'TD', 'Rec', 'Yds', 'TD', 'Solo', 'Sk',
       'Int'],
      dtype='object')

In [168]:
main_df.to_csv('nfl_top_100.csv', index=False)